### ISSUE TITLE
Mixed content with assets

### ISSUE THREAD

**Issue by renchap** [sysadmin-fr/bestPractices#1]
When loading the site over HTTPS you get :

> Mixed Content: The page at 'https://sysadmin-fr.github.io/bestPractices/' was loaded over HTTPS, but requested an insecure stylesheet 'http://sysadmin-fr.github.io/bestPractices/css/syntax.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by frbayart** [comment]
I have push a fix

**Comment by camlafit** [comment]
It's incorrect we must have also a correct url in local mode

**Comment by frbayart** [comment]
may be you can configure /bestPratice on your local configuration ?

**Comment by frbayart** [comment]
@camlafit try jekyll serve --baseurl '/bestPractices'
